name: databricks_cicd
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - flake8
  - pip
  - pip:
    - black==20.8b1
    - databricks-cli==0.14.3
    - databricks-connect==7.3.11
    - pytest==6.2.4
    - pytest-mock==3.6.1
    - python-dotenv==0.17.1
